#!/usr/bin/env bash
set -Eeuo pipefail

PROJECT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)
ENV_FILE="$PROJECT_DIR/.env"

usage() {
    cat <<'EOF'
Usage: ./scripts/setup.sh [options]

Create .env and local data directories for dsh AIO.

Options:
  --host HOST       Public hostname or IP (default: localhost)
  --user USER       Basic Auth username (default: admin)
  --http            Use plain HTTP instead of the default self-signed HTTPS
  --force           Replace an existing .env file
  -h, --help        Show this help

The Basic Auth password is always read interactively and is never written in
plain text. This script only prepares configuration; run
"docker compose up -d" afterwards. The self-signed certificate is generated
by Nginx on first start with a 100-year validity period; it is not
automatically renewed.
EOF
}

die() {
    printf 'Error: %s\n' "$1" >&2
    exit 1
}

require_command() {
    command -v "$1" >/dev/null 2>&1 || die "missing required command: $1"
}

public_host=""
basic_user="admin"
basic_user_explicit="false"
self_signed="true"
force="false"

while (($# > 0)); do
    case "$1" in
        --host)
            (($# >= 2)) || die "--host requires a value"
            public_host="$2"
            shift 2
            ;;
        --host=*)
            public_host="${1#*=}"
            shift
            ;;
        --user)
            (($# >= 2)) || die "--user requires a value"
            basic_user="$2"
            basic_user_explicit="true"
            shift 2
            ;;
        --user=*)
            basic_user="${1#*=}"
            basic_user_explicit="true"
            shift
            ;;
        --http)
            self_signed="false"
            shift
            ;;
        --force)
            force="true"
            shift
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        *)
            die "unknown option: $1 (use --help for usage)"
            ;;
    esac
done

require_command openssl

if [[ -e "$ENV_FILE" && "$force" != "true" ]]; then
    die "$ENV_FILE already exists; use --force only if you intend to replace it"
fi

if [[ -z "$public_host" ]]; then
    read -r -p 'Public hostname or IP [localhost]: ' entered_host || entered_host=""
    public_host="${entered_host:-localhost}"
fi

[[ -n "$public_host" ]] || die "public hostname or IP cannot be empty"
[[ "$public_host" != *[!A-Za-z0-9.:-]* ]] || die "hostname/IP contains unsupported characters"

if [[ "$public_host" == *:* ]]; then
    trusted_host="[$public_host]:3080"
else
    trusted_host="$public_host:3080"
fi

if [[ ! "$basic_user" =~ ^[A-Za-z0-9._-]+$ ]]; then
    die "Basic Auth username may contain only letters, numbers, '.', '_' and '-'"
fi

if [[ "$basic_user_explicit" != "true" ]]; then
    read -r -p 'Basic Auth username [admin]: ' entered_user || entered_user=""
    basic_user="${entered_user:-admin}"
    [[ "$basic_user" =~ ^[A-Za-z0-9._-]+$ ]] || die "invalid Basic Auth username"
fi

printf 'Create the Basic Auth password. It will not be stored in plain text.\n'
read -r -s -p 'Password: ' password || die 'password input is required'
printf '\n'
read -r -s -p 'Confirm password: ' password_confirm || die 'password confirmation is required'
printf '\n'
[[ -n "$password" ]] || die 'password cannot be empty'
[[ "$password" == "$password_confirm" ]] || die 'passwords do not match'

auth_hash=$(printf '%s\n' "$password" | openssl passwd -apr1 -stdin)
unset password password_confirm
[[ -n "$auth_hash" ]] || die 'failed to generate the Basic Auth hash'

allowlist_enabled="false"
allowlist=""
read -r -p 'Enable an IP allowlist? [y/N]: ' allowlist_answer || allowlist_answer=""
case "$allowlist_answer" in
    y|Y|yes|YES|Yes)
        read -r -p 'Allowed IPs/CIDRs (comma-separated): ' allowlist || allowlist=""
        [[ -n "$allowlist" ]] || die 'an enabled IP allowlist cannot be empty'
        allowlist_enabled="true"
        ;;
    *)
        ;;
esac

mkdir -p "$PROJECT_DIR/.dsh" "$PROJECT_DIR/workspace" "$PROJECT_DIR/nginx/certs"
chmod 700 "$PROJECT_DIR/.dsh" "$PROJECT_DIR/workspace" "$PROJECT_DIR/nginx/certs"

umask 077
tmp_env=$(mktemp "$ENV_FILE.tmp.XXXXXX")
cleanup() {
    rm -f "$tmp_env"
}
trap cleanup EXIT

{
    printf '# Generated by scripts/setup.sh; edit as needed.\n'
    printf 'DSH_TRUSTED_HOST=%s\n' "$trusted_host"
    printf 'DSH_ALLOW_REMOTE_PRIVILEGED=true\n'
    printf 'DSH_WORKSPACE_PATH=./workspace\n'
    printf 'NGINX_SELF_SIGNED_CERT=%s\n' "$self_signed"
    printf 'NGINX_CERT_DAYS=36500\n'
    printf 'NGINX_SERVER_NAME=%s\n' "$public_host"
    printf 'NGINX_IP_ALLOWLIST_ENABLED=%s\n' "$allowlist_enabled"
    printf 'NGINX_IP_ALLOWLIST=%s\n' "$allowlist"
    printf 'NGINX_BASIC_AUTH_USER=%s\n' "$basic_user"
    printf "NGINX_BASIC_AUTH_HASH='%s'\n" "$auth_hash"
} > "$tmp_env"
chmod 600 "$tmp_env"
mv -f "$tmp_env" "$ENV_FILE"
trap - EXIT

if [[ "$self_signed" == "true" ]]; then
    scheme="https"
else
    scheme="http"
    printf 'Warning: HTTP sends Basic Auth credentials without TLS.\n' >&2
fi

printf '\nConfiguration written to %s\n' "$ENV_FILE"
printf 'Run: docker compose up -d\n'
printf 'Then open %s://%s\n' "$scheme" "$trusted_host"
if [[ "$self_signed" == "true" ]]; then
    printf 'The first start will generate a self-signed certificate in nginx/certs/.\n'
fi
